name: image_size_getter_heic
description: A decoder for HEIC images with image_size_getter.
version: 1.0.1
homepage: https://github.com/CaiJingLong/dart_image_size_getter
repository: https://github.com/CaiJingLong/dart_image_size_getter

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies:
  image_size_getter:
    path: ../library
  bmff: ^1.4.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
